FROM mariadb:10.5
LABEL author="genesis"
ENV MYSQL_ROOT_PASSWORD "genesis21"
ENV MYSQL_DATABASE "semana18"
ENV MYSQL_USER "genesis"
ENV MYSQL_PASSWORD "genesis21"
COPY Users.sql /docker-entrypoint-initdb.d/
EXPOSE 3306