FROM mariadb:10.5
LABEL author="javier"
ENV MYSQL_ROOT_PASSWORD "javier21"
ENV MYSQL_DATABASE "semana18"
ENV MYSQL_USER "javier"
ENV MYSQL_PASSWORD "javier21"
COPY Users.sql /docker-entrypoint-initdb.d/
EXPOSE 3306