FROM mariadb:10.5
LABEL author="haydee"
ENV MYSQL_ROOT_PASSWORD "haydee21"
ENV MYSQL_DATABASE "semana18"
ENV MYSQL_USER "haydee"
ENV MYSQL_PASSWORD "haydee21"
COPY Users.sql /docker-entrypoint-initdb.d/
EXPOSE 3306